[workspace]
members = [
    "ghash",
    "poly1305",
    "polyval"
]
resolver = "2"

[profile.dev]
opt-level = 2

[patch.crates-io]
universal-hash = { git = "https://github.com/RustCrypto/traits", branch = "uhf/v0.5" }
