name: ghash

on:
  pull_request:
    paths:
      - ".github/workflows/ghash.yml"
      - "ghash/**"
      - "Cargo.*"
  push:
    branches: master
    paths:
      - "ghash/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: ghash

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.81.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --no-default-features --release --target ${{ matrix.target }}

  benches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - run: cargo build --benches

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.81.0 # MSRV
          - stable
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - run: |
        cargo check --all-features
        cargo test --no-default-features
        cargo test
        cargo test --all-features
